# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TIL - Today I Learned - khebbie
email: khebbie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On this site I will publish TIL's
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://khebbie.github.io" # the base hostname & protocol for your site
github_username:  khebbie

# Build settings
markdown: kramdown
